global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets:
          - 'host.docker.internal:9090' # Prometheus itself
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitExchange:3001']