services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ['start-dev']
    ports:
      - "8089:8080" 
    volumes:
      - ../keycloak-content:/opt/keycloak/data
